server:
 port: 8666

spring:
 datasource:
  url: jdbc:mysql://localhost:3306/test
  username: test
  password: test
 jpa:
  hibernate:
   ddl-auto: update
 application:
  name: identity-service  
   
   
eurek:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/   


 
